### ISSUE TITLE
Question: What license is this code made available under?

### ISSUE THREAD

**Issue by rathboma** [cleverbrush/framework#53]
It'd be great if you could add a LICENSE file to identify the license you're making them available under, EG MIT, Apache2.

Thanks!

**Comment by andrewzolotukhin** [comment]
Hi! It's under BSD license you can use it and feel free to contribute. I'll add the file soon, thanks.

**Comment by andrewzolotukhin** [comment]
`LICENSE` file has been added to the repo.
